title:             skylic의 개인 공간
email:             siv37s@naver.com
description:       ...
author:            skylic
baseurl:           "/"
url:               "http://skylic.github.io"

# Social Profiles
twitter_username:
github_username:   skylic
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
